# Generated by Django 4.0.3 on 2022-04-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='SystemName',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
