# Generated by Django 4.0.3 on 2022-04-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_userprofile_systemname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gmail',
            field=models.CharField(default=13, max_length=255),
            preserve_default=False,
        ),
    ]
